# 评测结果
ACCEPTED        = 'ACCEPTED'
WRONG_ANSWER    = 'WRONG_ANSWER'
BUILD_FAILED    = 'BUILD_FAILED'
COMPILE_ERROR   = 'COMPILE_ERROR'
RUNTIME_ERROR   = 'RUNTIME_ERROR'
OTHER_ERROR     = 'OTHER_ERROR'

# 评测类型
TYPE_LLVM       = 'llvm'
TYPE_QEMU       = 'qemu'
TYPE_RPI        = 'rpi'
TYPE_RPI_ELF    = 'rpi-elf'
TYPE_INTERPRET  = 'interpret'
