# 评测结果
ACCEPTED        = 1
WRONG_ANSWER    = 2
BUILD_FAILED    = 3
COMPILE_ERROR   = 4
RUNTIME_ERROR   = 5
OTHER_ERROR     = 6

verdict_name = {
    ACCEPTED: 'ACCEPTED',
    WRONG_ANSWER: 'WRONG_ANSWER',
    BUILD_FAILED: 'BUILD_FAILED',
    COMPILE_ERROR: 'COMPILE_ERROR',
    RUNTIME_ERROR: 'RUNTIME_ERROR',
    OTHER_ERROR: 'OTHER_ERROR',
}

TYPE_LLVM       = 'llvm'
TYPE_QEMU       = 'qemu'
TYPE_RPI        = 'rpi'
TYPE_RPI_ELF    = 'rpi-elf'
TYPE_INTERPRET  = 'interpret'
