# 评测结果
ACCEPTED = 1
WRONG_ANSWER = 2
BUILD_FAILED = 3
RUNTIME_ERROR = 4
OTHER_ERROR = 5

verdict_id2name = {
    ACCEPTED: 'ACCEPTED',
    WRONG_ANSWER: 'WRONG_ANSWER',
    BUILD_FAILED: 'BUILD_FAILED',
    RUNTIME_ERROR: 'RUNTIME_ERROR',
    OTHER_ERROR: 'OTHER_ERROR',
}